services:
  - type: web
    name: video-downloader
    env: docker
    dockerfilePath: ./Dockerfile
    region: oregon
    plan: free
    disk:
      name: downloads
      mountPath: /app/downloads
      sizeGB: 1
    envVars:
      - key: PORT
        value: 5000
      - key: PYTHONUNBUFFERED
        value: 1